version: '3'

services:
  dod-policy-crawler:
    build: .
    env_file:
    - .env
    command: tail -f /dev/null
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./dbdata/:/data/db
    env_file:
    - .env